#!/bin/bash
# BitMinti Portable Linux Build Script (Depends-based)
# Builds static binaries that run on most Linux distributions
# Usage: ./build-linux.sh

set -e

# Resolve locations
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

echo "========================================"
echo "BitMinti Portable Linux Build"
echo "========================================"
echo "Target: x86_64-pc-linux-gnu"
echo "Project Root: $PROJECT_ROOT"
echo ""

# 1. Build Dependencies
echo "Step 1: Building dependencies in depends/..."
echo "This ensures static linking and high compatibility."
echo ""

cd "$PROJECT_ROOT/depends"
# Build for generic 64-bit Linux with all static libs
make HOST=x86_64-pc-linux-gnu -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)
cd ..

# 2. Configure with Depends Toolchain
echo ""
echo "Step 2: Configuring CMake..."
rm -rf "$PROJECT_ROOT/build-linux"
mkdir -p "$PROJECT_ROOT/build-linux"

# Use the toolchain file generated by the depends system
cmake -B "$PROJECT_ROOT/build-linux" \
    -DCMAKE_TOOLCHAIN_FILE="$PROJECT_ROOT/depends/x86_64-pc-linux-gnu/toolchain.cmake" \
    -DBUILD_GUI=OFF \
    -DBUILD_TESTS=OFF \
    -DBUILD_BENCH=OFF

# 3. Build Binaries
echo ""
echo "Step 3: Building Binaries..."
echo ""

cmake --build "$PROJECT_ROOT/build-linux" --target bitmintid bitminti-cli -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)

echo ""
echo "========================================"
echo "✅ Portable Linux Build Complete!"
echo "========================================"
echo "Binaries:"
echo "  $PROJECT_ROOT/build-linux/src/bitmintid"
echo "  $PROJECT_ROOT/build-linux/src/bitminti-cli"
echo ""
echo "These binaries are static and portable."
